# Use the newer container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Cache pip downloads
cache:
    directories:
      - $HOME/.pip-cache/

language: python

python:
    - '2.7.13'
    - '3.5'
    - '3.6'

env:
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.2.2
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.3
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.4
    - DJANGO=Django==1.8.18 OSCAR=django-oscar==1.5
    - DJANGO=Django==1.10.8 OSCAR=django-oscar==1.4
    - DJANGO=Django==1.10.8 OSCAR=django-oscar==1.5
    - DJANGO=Django==1.11.5 OSCAR=django-oscar==1.5

before_install:
    - pip install codecov

install:
    - pip install $OSCAR
    - pip install $DJANGO -e .
    - make install

script:
    - make coverage

after_success:
  - codecov
