language: python

dist: xenial

matrix:
  include:
    - { python: "2.7", env: "DJANGO='Django>=1.11,<2.0' OSCAR='django-oscar>1.5,<1.6'" }
    - { python: "2.7", env: "DJANGO='Django>=1.11,<2.0' OSCAR='django-oscar>1.6,<1.7'" }

    - { python: "3.5", env: "DJANGO='Django>=1.11,<2.0' OSCAR='django-oscar>1.5,<1.6'" }
    - { python: "3.5", env: "DJANGO='Django>=1.11,<2.0' OSCAR='django-oscar>1.6,<1.7'" }
    - { python: "3.5", env: "DJANGO='Django>=2.1,<2.2' OSCAR='django-oscar>1.6,<1.7'" }

    - { python: "3.6", env: "DJANGO='Django>=1.11,<2.0' OSCAR='django-oscar>1.5,<1.6'" }
    - { python: "3.6", env: "DJANGO='Django>=1.11,<2.0' OSCAR='django-oscar>1.6,<1.7'" }
    - { python: "3.6", env: "DJANGO='Django>=2.1,<2.2' OSCAR='django-oscar>1.6,<1.7'" }

    - { python: "3.7", env: "DJANGO='Django>=1.11.17,<2.0' OSCAR='django-oscar>1.5,<1.6'" }
    - { python: "3.7", env: "DJANGO='Django>=1.11.17,<2.0' OSCAR='django-oscar>1.6,<1.7'" }
    - { python: "3.7", env: "DJANGO='Django>=2.1,<2.2' OSCAR='django-oscar>1.6,<1.7'"}

before_install:
    - pip install codecov

install:
    - pip install $OSCAR $DJANGO
    - if ! [ ${DJANGO} == "Django>=1.11,<2.0" ]; then pip install "djangorestframework>=3.7"; fi
    - make install
    - pip freeze

script:
    - make coverage

after_success:
  - codecov
