language: python
os: linux
dist: xenial

stages:
  - lint
  - test

addons:
  apt:
    packages:
      - sqlite3

jobs:
  fast_finish: true

  include:
    - stage: lint
      python: 3.7
      env: "DJANGO='Django>=2.2,<3' OSCAR='django-oscar>=2.0,<2.1'"
      script: make lint

    - stage: test
      python: 3.5
      env: "DJANGO='Django>=2.1,<2.2' OSCAR='django-oscar>=2.0,<2.1'"
      script: make coverage
    - stage: test
      python: 3.6
      env: "DJANGO='Django>=2.1,<2.2' OSCAR='django-oscar>=2.0,<2.1'"
      script: make coverage
    - stage: test
      python: 3.7
      env: "DJANGO='Django>=2.1,<2.2' OSCAR='django-oscar>=2.0,<2.1'"
      script: make coverage
    - stage: test
      python: 3.5
      env: "DJANGO='Django>=2.2,<3' OSCAR='django-oscar>=2.0,<2.1'"
      script: make coverage
    - stage: test
      python: 3.6
      env: "DJANGO='Django>=2.2,<3' OSCAR='django-oscar>=2.0,<2.1'"
      script: make coverage
    - stage: test
      python: 3.7
      env: "DJANGO='Django>=2.2,<3' OSCAR='django-oscar>=2.0,<2.1'"
      script: make coverage

    - stage: test
      python: 3.7
      env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"
      script: make coverage

  allow_failures:
    - env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"

before_install:
    - sudo add-apt-repository ppa:jonathonf/backports -y
    - sudo apt-get update -q && sudo apt-get install -y sqlite3
    - pip install codecov

install:
    - pip install $OSCAR $DJANGO
    - make install
    - pip freeze

after_success:
  - codecov
