name: CI
on: [push, pull_request]

defaults:
  run:
    working-directory: ./src

jobs:
  run-linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        path: ./src
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
         python-version: '3.11'
    - name: Install all dependencies
      run: make install
    - name: Run all linting
      run: make lint
    - name: Upload src dir as artefact
      uses: actions/upload-artifact@v4
      with:
        name: src
        path: ./src

  run-tests:
    needs: run-linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        django-version: ["3.2", "4.2", "5.2"]
        oscar-version: ["3.2", "4.0"]
        exclude:
          - python-version: "3.13"
            django-version: "3.2"
          - python-version: "3.13"
            django-version: "4.2"
          - python-version: "3.12"
            django-version: "3.2"
          - python-version: "3.12"
            django-version: "4.2"
          - python-version: "3.11"
            django-version: "3.2"
          - python-version: "3.8"
            django-version: "5.2"
          - python-version: "3.8"
            oscar-version: "4.0"
    steps:
      - name: Download src dir
        uses: actions/download-artifact@v4
        with:
          name: src
          path: ./src
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
           python-version: ${{ matrix.python-version }}
      - name: Install all dependencies
        run: |
          pip install -e .[dev]
          pip install "django~=${{ matrix.django-version }}.0"
          pip install "django-oscar~=${{ matrix.oscar-version }}.0"
          make install
      - name: Show all versions
        run: pip list
      - name: Run the testsuite
        run: make coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
